config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :votes, except: [:destroy, :edit]
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  get 'user', to: 'users#show', as: 'user'
  
  resources :restaurants, except: :destroy do
    put :up_vote
    put :down_vote
    put :favorite
  end
  root 'restaurants#index', as: 'restaurants_index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, :location, presence: true
#  has_many :users
  has_many :votes
  has_many :comments
  has_many :favorite_restaurants
  has_many :favorited_by, through: :favorite_restaurants, source: :user

  def self.up_vote restaurant, user
    Vote.create(:user_id => user.id, :restaurant_id => restaurant.id, :up_vote => 1, :down_vote => 0)
  end

  def self.down_vote restaurant, user
    Vote.create(:user_id => user.id, :restaurant_id => restaurant.id, :up_vote => 0, :down_vote => 1)
  end

  def get_total_up_votes
    self.votes.sum(:up_vote)
  end

  def get_total_down_votes
    self.votes.sum(:down_vote)
  end

  def self.search_by_name name
    if name 
      where('name LIKE ?', "%#{name}%")
    end
  end

  def self.search_by_location location
    if location 
      where('location LIKE ?', "%#{location}%")
    end
  end

  def self.leave_comment
    Comment.new
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show] 

  # GET /restaurants
  # GET /restaurants.json
  def index
      if params[:name]
        @restaurants = Restaurant.search_by_name(params[:name])
      elsif params[:location]
        @restaurants = Restaurant.search_by_location(params[:location])
      else
        @restaurants = Restaurant.all
      end
      @user = current_user
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)
 #   @restaurant.up_votes = 0;
 #   @restaurant.down_votes = 0;
    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def up_vote
    @restaurant = Restaurant.find(params[:restaurant_id])
    Restaurant.up_vote(@restaurant, current_user)
    redirect_to '/'
  end

  def down_vote
    @restaurant = Restaurant.find(params[:restaurant_id])
    Restaurant.down_vote(@restaurant, current_user)
    redirect_to '/'
  end

  def leave_comment
    Restaurant.leave_comment
    redirect_to @restaurant
  end

  def favorite 
    @restaurant = Restaurant.find(params[:restaurant_id])
    if current_user.favorites.include? @restaurant
      redirect_to '/', notice: 'You have already favorited ' + @restaurant.name
    else   
      current_user.favorites << @restaurant
      redirect_to '/', notice: 'You favorited ' + @restaurant.name
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :location, :up_votes, :down_votes)
    end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<%= form_with(model: restaurant, local: true) do |form| %>
  <% if restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="form-group">
      <div class="field">
        <%= form.label :name %>
        <%= form.text_field :name %>
      </div>
    </div>
    <div class="form-group">
      <div class="field">
        <%= form.label :location %>
        <%= form.text_field :location %>
      </div>
    </div>
    <div class="actions">
      <%= form.submit %>
    </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Edit Restaurant</h1>
<div class="new border rounded">
  <%= render 'form', restaurant: @restaurant %>
</div>
<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<% if user_signed_in? %>
 | <%= link_to 'User Summary', @user %>
<% end %>
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>
<div class="navbar navbar-fixed">
<h1>Restaurants</h1>
<div class="search" >
  <table>
    <thead>
      <tr>
        <th>Search by Name</th>
        <th>Search by Location</th>
      </tr>
    </thead>
    <tbody>
      <td id="search_by_name">
        <%= form_tag(restaurants_path, :method => :get) do %>
          <%= text_field_tag :name, params[:name] %>
          <%= submit_tag 'Search', name: nil, id: 'search_by_name'%>
        <% end %>
    </td>
    <td id="search_by_location">
      <%= form_tag(restaurants_path, :method => :get) do %>
        <%= text_field_tag :location, params[:location] %>
        <%= submit_tag 'Search', name: nil, id: 'search_by_location'%>
      <% end %>
    </td>
  </tbody>
</table>
</div>
</div>
<div class="table-striped border rounded">
<table class="restaurants">
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th>Will Split Check</th>
      <th>Will Not Split Check</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td id="name"><%= restaurant.name %></td>
        <td id="location"><%= restaurant.location %></td>
        <td id="up_votes"><%= restaurant.get_total_up_votes %></td>
        <td id="down_votes"><%= restaurant.get_total_down_votes %></td>
        <td><%= link_to 'Show', restaurant %></td>
        <% if user_signed_in? %>
          <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
          <td><%= button_to 'Will Split Check', restaurant_up_vote_path(restaurant), :method => :put, :restarant_id => restaurant.id %></td>
          <td><%= button_to 'Will Not Split Check', restaurant_down_vote_path(restaurant), :method => :put, :restaurant_id => restaurant.id %></td>
	  <td><%= button_to 'Add to Favorites', restaurant_favorite_path(restaurant), :method => :put, :restaurant_id => restaurant.id  %> </td>
          <td><%= link_to 'Leave a Comment', restaurant %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<% if user_signed_in? %>
  <%= link_to 'Add New Restaurant', new_restaurant_path %> 
<% end %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<div class="new border rounded">
  <%= render 'form', restaurant: @restaurant %>
</div>
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @restaurant.location %>
</p>

<p>
  <strong>Up votes:</strong>
  <%= @restaurant.get_total_up_votes %>
</p>

<p>
  <strong>Down votes:</strong>
  <%= @restaurant.get_total_down_votes %>
</p>
<% if user_signed_in? %>
  <%= form_for(Restaurant.leave_comment) do |f| %>
    <div class="form-group">
      <div class="field">
        <%= f.label :comment %>
        <div class="hidden-field"><%= f.text_field :user_id, value: current_user.id %></div>
        <div class="hidden-field"><%= f.text_field :restaurant_id, value: @restaurant.id %></div>
        <%= f.text_area :content, style: 'vertical-align: top' %>
      </div>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
<% end %>
<div class="table-striped border rounded">

<% if @restaurant.comments.count > 0 %>
  <table class="restaurants">
    <thead>
      <tr>
        <th>User</th>
        <th>Comment</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @restaurant.comments.each do |comment| %>
        <tr>
          <td id="user"><%= comment.user.email %></td>
          <td id="comment"><%= comment.content %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<% if user_signed_in? %>
  <%= link_to 'Edit', edit_restaurant_path(@restaurant) %> 
<% end %>