config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :votes, except: [:destroy, :edit]
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  get 'user', to: 'users#show', as: 'user'
  
  resources :restaurants, except: :destroy do
    put :up_vote
    put :down_vote
    put :favorite
  end
  root 'restaurants#index', as: 'restaurants_index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/vote.rb
class Vote < ApplicationRecord 
  validates :up_vote, numericality: {greater_than_or_equal_to: 0}
  validates :down_vote, numericality: {greater_than_or_equal_to: 0}
  belongs_to :user
  belongs_to :restaurant
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :set_vote, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: :show
  # GET /votes
  # GET /votes.json
  def index
    @votes = Vote.all
    @user = current_user
  end

  # GET /votes/1
  # GET /votes/1.json
  def show
  end

  # GET /votes/new
  def new
    @vote = current_user.votes.build
  end

  # GET /votes/1/edit
  def edit
  end

  # POST /votes
  # POST /votes.json
  def create
    @vote = Vote.new(vote_params)

    respond_to do |format|
      if @vote.save
        format.html { redirect_to @vote, notice: 'Vote was successfully created.' }
        format.json { render :show, status: :created, location: @vote }
      else
        format.html { render :new }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /votes/1
  # PATCH/PUT /votes/1.json
  def update
    respond_to do |format|
      if @vote.update(vote_params)
        format.html { redirect_to @vote, notice: 'Vote was successfully updated.' }
        format.json { render :show, status: :ok, location: @vote }
      else
        format.html { render :edit }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /votes/1
  # DELETE /votes/1.json
  def destroy
    @vote.destroy
    respond_to do |format|
      format.html { redirect_to votes_url, notice: 'Vote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vote
      @vote = Vote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vote_params
      params.require(:vote).permit(:user_id, :restaurant_id, :up_vote, :down_vote)
    end
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/votes/_form.html.erb
<%= form_with(model: vote, local: true) do |form| %>
  <% if vote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vote.errors.count, "error") %> prohibited this vote from being saved:</h2>

      <ul>
      <% vote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :restaurant_id %>
    <%= form.text_field :restaurant_id %>
  </div>

  <div class="field">
    <%= form.label :up_vote %>
    <%= form.number_field :up_vote %>
  </div>

  <div class="field">
    <%= form.label :down_vote %>
    <%= form.number_field :down_vote %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/votes/edit.html.erb
<h1>Editing Vote</h1>

<%= render 'form', vote: @vote %>

<%= link_to 'Show', @vote %> |
<%= link_to 'Back', votes_path %>

app/views/votes/index.html.erb
<p id="notice"><%= notice %></p>
<div class="navbar navbar-fixed">
<h1>Votes</h1>
</div>
<div class="table-striped border rounded">
<table class="restaurants">
  <thead>
    <tr>
      <th>User</th>
      <th>Restaurant</th>
      <th>Up vote</th>
      <th>Down vote</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @votes.each do |vote| %>
      <tr>
        <td><%= vote.user.email %></td>
        <td><%= vote.restaurant.name %></td>
        <td><%= vote.up_vote %></td>
        <td><%= vote.down_vote %></td>
        <td><%= link_to 'Show', vote %></td>
      <%#  <td><%= link_to 'Edit', edit_vote_path(vote) %></td>
     <%#   <td><%= link_to 'Destroy', vote, method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<%= link_to 'New Vote', new_vote_path %>

app/views/votes/new.html.erb
<h1>New Vote</h1>

<%= render 'form', vote: @vote %>

<%= link_to 'Back', votes_path %>

app/views/votes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @vote.user.email %>
</p>

<p>
  <strong>Restaurant:</strong>
  <%= @vote.restaurant.name %>
</p>

<p>
  <strong>Up vote:</strong>
  <%= @vote.up_vote %>
</p>

<p>
  <strong>Down vote:</strong>
  <%= @vote.down_vote %>
</p>

<%#<%= link_to 'Edit', edit_vote_path(@vote) %> 
<%= link_to 'Back', votes_path %>